### ISSUE TITLE
pothos v0.3 features checklist 

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos#29]
This is probably an issue that will accumulate over time. Basically we are planning for what's in 0.3, and at the time of writing 0.2 with whatever patches will be tagged off and frozen. So we have API changes (mostly additions), component reorganization, and new features and improvements:

### Splitting up components

Soapy SDR will no longer host submodules. Pothos-blocks is split into pothos-comms, while some other misc library functions also move into comms. Pothos-widgets is split into pothos-plotters with all Qwt dependent blocks.

* [x] Plotters: https://github.com/pothosware/pothos/issues/28
* [x] Comms: https://github.com/pothosware/pothos/issues/24
* [x] Soapy: https://github.com/pothosware/SoapySDR/issues/24

### Removing components

Also, remove pothos-opencl, and pothos-java from the master projects. These will still remain and installable toolkits, but their use is currently limited or the dependency libraries are complicated (especially opencl).

*  [x] remove pothos-java toolkit from master project
*  [x] remove pothos-opencl toolkit from master project

### Network improvments

* [x] Support binary serialization: https://github.com/pothosware/pothos-library/issues/106
* [ ] Pothos proxy server SSL: https://github.com/pothosware/pothos/issues/20
* [x] Redo RPC layer: https://github.com/pothosware/pothos-library/issues/107

### Framework/block API improvements

*  [ ] Buffer allocator: https://github.com/pothosware/pothos-library/issues/103
*  [x] Port alias: https://github.com/pothosware/pothos-library/issues/102

### Framework/topology API improvements

*  [ ] Connection markup to simplify things like buses: https://github.com/pothosware/pothos-library/issues/43
*  [ ] Improved JSON support (hierarchies, variables/expressions, remote distribution): https://github.com/pothosware/pothos-library/issues/86

## SDR blocks additions

* [x] GPIO access: https://github.com/pothosware/SoapySDR/issues/22, https://github.com/pothosware/pothos-sdr/issues/8
* [ ] Populating options based on hardware: This will be a combined effort of this issue https://github.com/pothosware/pothos-gui/issues/75 and adding query hooks to the SDR blocks

## GUI improvements

Probably the number one improvement should be fixing the evaluator to do the minimum amount of work. Right now the background evaluation is stupid and re-submits in the background on every block. Large flowgraphs get sluggish, and they shouldnt when there are actually no changes. Also the change detection logic could be better anyhow.

* [ ] Implement better topology evaluator: https://github.com/pothosware/pothos-gui/issues/97
* [ ] The way of making connections could be way more useful and intuitive: https://github.com/pothosware/pothos-gui/issues/97

**Comment by guruofquality** [comment]
Version v0.3 has been tagged. We going for more releases more often. The boxes not checked will be part of future releases.
