### ISSUE TITLE
0.4.0 release TODO list

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos#94]
* [x] merge cpp11 work - https://github.com/pothosware/pothos/issues/91
* [x] list API additions in the changelog
* [x] BlocksCodingGuide - switch to BlockRegistry and Block::emitSignal() calls
* [x] upload doxygen html to gh-pages
* [x] use BlockRegistry in comms + blocks unit tests
* [x] use Block::emitSignal() in comms, blocks, sdr, widgets, plotters

**Comment by guruofquality** [comment]
* 0.4.0 tag is up
* new doxygen
* updated coding guide
* binaries are in the works
